# Generated by Django 4.2.3 on 2023-09-14 15:57

import django.contrib.auth.models
from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_client_options_alter_client_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='client',
            managers=[
                ('client_manager', django.db.models.manager.Manager()),
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
