# Generated by Django 4.2.3 on 2023-11-13 17:15

import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_client_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='client',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=255, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='client',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='client',
            name='username',
            field=models.CharField(max_length=255, unique=True, validators=[django.core.validators.MinLengthValidator(limit_value=5)], verbose_name='Username'),
        ),
    ]
