[tool.poetry]
name = "walkershop"
version = "0.1.0"
description = ""
authors = ["TarhanovM <tarmd@ya.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
django = "^4.2.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
