# Generated by Django 4.2.3 on 2023-11-21 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_clientaudiencecategory_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudienceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audience_name', models.CharField(max_length=127)),
                ('audience_description', models.TextField(max_length=255)),
                ('categories', models.ManyToManyField(to='cart.productcategory')),
            ],
            options={
                'verbose_name': 'Audience category',
                'verbose_name_plural': 'Audience categories',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductSubcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory_name', models.CharField(max_length=127)),
            ],
            options={
                'verbose_name': 'Product subcategory',
                'verbose_name_plural': 'Product subcategories',
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='ClientAudienceCategory',
        ),
    ]
