# Generated by Django 4.2.3 on 2024-01-30 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_productcategory_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cart.productsubcategory'),
        ),
        migrations.AlterField(
            model_name='audiencecategory',
            name='categories',
            field=models.ManyToManyField(related_name='audience_categories', to='cart.productcategory'),
        ),
        migrations.AlterModelTable(
            name='productsubcategory',
            table='product_subcategory',
        ),
    ]
